// src/lib/components/Contact.svelte
<div class="container mx-auto mt-40 p-5">
    <h2 class="my-5 text-center text-2xl">
        <i class="bi bi-envelope" /> Get in touch
    </h2>
    <hr class="mx-auto h-1 w-3/4 rounded border-0 bg-zinc-700 dark:bg-zinc-200" />

    <p class="my-5 text-center">Do you want to contact me? Leave me a message right here!</p>

    <form action="https://getform.io/f/866900ee-a284-48a0-b031-ab5931937dde" method="POST">
        <div class="mx-auto grid max-w-4xl md:grid-cols-2">
            <input class="m-3 rounded border bg-white/50 p-3 shadow dark:bg-zinc-800" type="text" name="name" placeholder="Your name" />
            <input class="m-3 rounded border bg-white/50 p-3 shadow dark:bg-zinc-800" type="email" name="email" placeholder="your_email@example.com" />
            <textarea class="m-3 rounded border bg-white/50 p-3 shadow dark:bg-zinc-800 md:col-span-2" name="message" placeholder="Write your message..." />
        </div>
        <div class="flex justify-center">
            <button class="rounded bg-teal-500 p-2 px-4 text-white shadow" type="submit"> Send </button>
        </div>
    </form>
    <br />
    <br />
    <br />
</div>

// components/sections/Contact.tsx
const Contact = () => (
    <div className='container mx-auto mt-40 p-5'>
        <h2 className='text-2xl text-center my-5'>
            <i className='bi bi-envelope'></i> Get in touch
        </h2>
        <hr className='bg-zinc-700 dark:bg-zinc-200 border-0 rounded h-1 w-3/4 mx-auto' />

        <p className='text-center my-5'>Do you want to contact me? Leave me a message right here!</p>

        <form action='https://getform.io/f/866900ee-a284-48a0-b031-ab5931937dde' method='POST'>
            <div className='grid md:grid-cols-2 max-w-4xl mx-auto'>
                <input
                    className='p-3 m-3 border shadow rounded bg-white/50 dark:bg-zinc-800'
                    type='text'
                    name='name'
                    placeholder='Your name'
                />
                <input
                    className='p-3 m-3 border shadow rounded bg-white/50 dark:bg-zinc-800'
                    type='email'
                    name='email'
                    placeholder='your_email@example.com'
                />
                <textarea
                    className='p-3 m-3 border shadow rounded bg-white/50 dark:bg-zinc-800 md:col-span-2'
                    name='message'
                    placeholder='Write your message...'
                />
            </div>
            <div className='flex justify-center'>
                <button className='bg-teal-500 shadow rounded text-white p-2 px-4' type='submit'>
                    Send
                </button>
            </div>
        </form>
        <br />
        <br />
        <br />
    </div>
)

export default Contact
