// src/routes/projects/+page.svelte
<script lang="ts">
    import { projects } from '$lib/config/projects'
    import { styles } from '$lib/config/styles'

    const badgeColors: Record<string, string> = {
        JavaScript: 'bg-yellow-500',
        TypeScript: 'bg-blue-500',
        NextJS: 'bg-black',
        Bootstrap: 'bg-purple-500',
        Tailwindcss: 'bg-fuchsia-500',
        MongoDB: 'bg-green-500',
        Docker: 'bg-sky-500',
        'React Native': 'bg-cyan-500',
        NuxtJS: 'bg-teal-500',
        Redis: 'bg-red-500',
        NestJS: 'bg-red-600',
        SvelteKit: 'bg-orange-400',
    }
</script>

<div class="animate__animated animate__fadeIn animate__faster container mx-auto my-20 p-5">
    <h2 class="my-5 text-center text-2xl">
        <i class="bi bi-github" /> Open source projects
    </h2>
    <hr class="mx-auto h-1 w-3/4 rounded border-0 bg-zinc-700 dark:bg-zinc-200" />
    <div class="mt-5 grid gap-4 lg:grid-cols-2 xl:grid-cols-3">
        {#each projects as project}
            <a
                href={'https://github.com/Dawichi/' + project.url}
                target="_blank"
                class={'animate__animated animate__zoomIn animate__faster rounded-lg p-4 md:py-4 md:px-10 ' + styles.card}
                rel="noreferrer"
            >
                <h4 class="mb-5 text-center text-xl">
                    <i class="bi bi-folder" />
                    {project.title}
                </h4>
                <div class="flex flex-wrap justify-center">
                    {#each project.tech as tech}
                        <span class={'m-1 rounded p-1 text-white md:text-sm ' + badgeColors[tech]}>
                            {tech}
                        </span>
                    {/each}
                </div>
                <div class="relative my-5 mx-auto h-48 w-full overflow-hidden rounded sm:h-72 md:h-96 lg:h-56">
                    <img src={project.image} alt={project.title} />
                </div>
                <p>{project.desc}</p>
                <br />
            </a>
        {/each}
    </div>
</div>

// pages/projects.tsx
import Image from 'next/image'
import { styles } from 'styles/styles.config'

interface Project {
    title: string
    image: string
    url: string
    desc: string
    tech: string[]
}

const Projects = () => (
    <div className='animate__animated animate__fadeIn animate__faster container mx-auto my-20 p-5'>
        <h2 className='my-5 text-center text-2xl'>
            <i className='bi bi-github'></i> Open source projects
        </h2>
        <hr className='mx-auto h-1 w-3/4 rounded border-0 bg-zinc-700 dark:bg-zinc-200' />
        <div className='mt-5 grid gap-4 lg:grid-cols-2 xl:grid-cols-3'>
            {projects_list.map((project: Project, idx_p: number) => (
                <a
                    key={idx_p}
                    href={'https://github.com/Dawichi/' + project.url}
                    target='_blank'
                    className={'animate__animated animate__zoomIn animate__faster rounded-lg py-4 px-10 ' + styles.card}
                    rel='noreferrer'
                >
                    <h4 className='mb-5 text-center text-xl'>
                        <i className='bi bi-folder'></i> {project.title}
                    </h4>
                    <div className='flex flex-wrap justify-center'>
                        {project.tech.map((tech: string, idx_t: number) => (
                            <span key={idx_t} className={'m-1 rounded p-1 text-white ' + tint(tech)}>
                                {tech}
                            </span>
                        ))}
                    </div>
                    <div className='relative my-5 mx-auto h-48 w-full overflow-hidden rounded sm:h-72 md:h-96 lg:h-56'>
                        <Image src={project.image} alt={project.title} layout='fill' />
                    </div>
                    <p>{project.desc}</p>
                    <br />
                </a>
            ))}
        </div>
    </div>
)

export default Projects

const tint = (tech: string) => {
    interface colorsKeyOf {
        JavaScript: string
        TypeScript: string
        NextJS: string
        Bootstrap: string
        Tailwindcss: string
        MongoDB: string
        Docker: string
        'React Native': string
    }

    const colors = {
        JavaScript: 'bg-yellow-500',
        TypeScript: 'bg-blue-500',
        NextJS: 'bg-black',
        Bootstrap: 'bg-purple-500',
        Tailwindcss: 'bg-fuchsia-500',
        MongoDB: 'bg-green-500',
        Docker: 'bg-sky-500',
        'React Native': 'bg-cyan-500',
    }
    return colors[tech as keyof colorsKeyOf]
}

const projects_list: Project[] = [
    {
        title: 'dawichi.dev',
        image: 'https://raw.githubusercontent.com/Dawichi/dawichi.dev/master/public/assets/img/showcase/screenshot_dark.png',
        url: 'dawichi.dev',
        desc: 'This website! Explore its code on GitHub',
        tech: ['NextJS', 'TypeScript', 'Tailwindcss'],
    },
    {
        title: 'Hexastats',
        image: 'https://raw.githubusercontent.com/Dawichi/hexastats/main/showcase.png',
        url: 'hexastats',
        desc: 'Custom graphs of stats from an online game',
        tech: ['NextJS', 'TypeScript', 'Tailwindcss'],
    },
    {
        title: 'Cloud app',
        image: 'https://raw.githubusercontent.com/Dawichi/cloud-app/main/sample2.png',
        url: 'cloud-app',
        desc: 'React MERN cloud storage app',
        tech: ['JavaScript', 'Bootstrap', 'MongoDB', 'Docker'],
    },
    {
        title: 'Hexakill',
        image: 'https://raw.githubusercontent.com/Dawichi/hexakill/main/showcase2.png',
        url: 'hexakill',
        desc: 'Basic RPG game made with TypeScript',
        tech: ['NextJS', 'TypeScript', 'Tailwindcss'],
    },
    {
        title: 'Hexakill CLI',
        image: 'https://raw.githubusercontent.com/Dawichi/hexakill-cli/main/showcase.png',
        url: 'hexakill-cli',
        desc: 'The terminal version of hexakill',
        tech: ['TypeScript'],
    },
    {
        title: 'Gif Search',
        image: 'https://raw.githubusercontent.com/Dawichi/gif-search/main/public/showcase.png',
        url: 'gif-search',
        desc: 'GIF search app, using the Giphy API',
        tech: ['NextJS', 'TypeScript', 'Tailwindcss'],
    },
    {
        title: 'Map Markers',
        image: 'https://raw.githubusercontent.com/Dawichi/map-markers/main/showcase.jpg',
        url: 'map-markers',
        desc: 'Mobile app to store markers in a map',
        tech: ['React Native'],
    },
]
